version: 2

sphinx:
  configuration: docs/conf.py

build:
  image: latest

python:
  version: 3.6
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs

sphinx:
  configuration: docs/conf.py
