language: python
python:
  - 3.6

stages:
  - test

jobs:
  include:
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      script:
        - pytest

before_deploy:
  - poetry config http-basic.pypi "$PYPI_USER" "$PYPI_PASS"
  - poetry run python bump_autobuild_version.py
  - poetry build


deploy:
  provider: script
  script: poetry publish

env:
  global:
    secure: lP0FETipTIt4Ear81lk+GoKmMy6oTdLUlLNY4tzla9CUPzmn8KM04fuUea1x1z8hV/oLhgiQBLvXb17j9jkAGSsCegW5hOe4KBraZS5dO4yYBuKA6DhE8sBniGfEuPmMZ6SCx9EUfwZcd1aIFaBGOIytXyeHee5Di7Vmis9doDt1ZNWaQzjIWhTnx7YnoVraAPN9ejD2hB4eNalYgiIzCOn76GmsUeb5IU7mK59YKE3C1yCxshRN3EUFsgyQDwaMFcmjhIhDn/JB3OJ7AlhrjO0c5COBf20icAcrOjAT9ogRWOCWpCWNXOm5VjPO3Z/V7mKbIctSdwuEtM7HWujExjToCvFq2UwhkQ+0up8CMWnSXA7TW8vZgyubqwBnOq8L7FaugIjjmElmCJ403/BJPCv131oJgcEuf7ksIgBjd9xTqPwOfgunlVZEos5DnsYe2MUW9Cr+H0UWJzDXgcYkRZbfQdtdLEC2n875VLzWz5UuEMo2SxLC8mfgigmVdYQvOwvfNwXkqova3nHiLAU9VyOQAV79k4q1yYtQ41ZX8wu/F1utws9Ozrx4maspSFH/YmWuUIUPG7mqIElLPIuhxTIdqrpXDRdk2754iC5RMKqWkTSVXQjjmtSNTNLn4QKmFvaSkiUrEGJwCEufR4JrdLrCrCSeWXFS/hOnvDZ8iks=
    secure: lP0FETipTIt4Ear81lk+GoKmMy6oTdLUlLNY4tzla9CUPzmn8KM04fuUea1x1z8hV/oLhgiQBLvXb17j9jkAGSsCegW5hOe4KBraZS5dO4yYBuKA6DhE8sBniGfEuPmMZ6SCx9EUfwZcd1aIFaBGOIytXyeHee5Di7Vmis9doDt1ZNWaQzjIWhTnx7YnoVraAPN9ejD2hB4eNalYgiIzCOn76GmsUeb5IU7mK59YKE3C1yCxshRN3EUFsgyQDwaMFcmjhIhDn/JB3OJ7AlhrjO0c5COBf20icAcrOjAT9ogRWOCWpCWNXOm5VjPO3Z/V7mKbIctSdwuEtM7HWujExjToCvFq2UwhkQ+0up8CMWnSXA7TW8vZgyubqwBnOq8L7FaugIjjmElmCJ403/BJPCv131oJgcEuf7ksIgBjd9xTqPwOfgunlVZEos5DnsYe2MUW9Cr+H0UWJzDXgcYkRZbfQdtdLEC2n875VLzWz5UuEMo2SxLC8mfgigmVdYQvOwvfNwXkqova3nHiLAU9VyOQAV79k4q1yYtQ41ZX8wu/F1utws9Ozrx4maspSFH/YmWuUIUPG7mqIElLPIuhxTIdqrpXDRdk2754iC5RMKqWkTSVXQjjmtSNTNLn4QKmFvaSkiUrEGJwCEufR4JrdLrCrCSeWXFS/hOnvDZ8iks=


