language: python
python:
  - 3.6
  - 3.8

env:
  jobs:
  - TF_VERSION=2.0
  - TF_VERSION=2.1
  - TF_VERSION=2.2
  global:
  - secure: "GOtVN6Ha+1qoaKOik5/MNmpjkp3Zc9faEVn3W1EnD++lKF6wFZCaSSxAvnN19fpbyuHc4j3/TQf7qxnHl4wtyiZk2nSi9ISv9ar3JdHhhsYMr/jPXbSZzrPJuZj1pIi+Xpyhd59C/0fQJwQkbiP3WpOfKUcv0miAcVBCwkMSabQ78Bv2Fi18ei4RKxgpAFI0pE8R0bt1M6dcCjx6yzA0NPmH9fFFCONv44vrY64gXLSQW7RL5MQGjyRFS8jnWOGWYZw6A+eGhb+pONBW3k+Jv5TRw9dm+aGjrO1upMOXHeQSg/AAl208IFVpv+7fDIGQ7Jl3aqzBXbQ98vXEABN5ABpTGuUFKodmS1ZA7xJMxvLXyyzDMSn6sUk3DdB3Tpv9r7iF1cW8AS5laXFuIFffLsxfPaOFFXP52bmOHmVZsqP9oUvdCQ2+Y3iAuGqlCg1mDUoLWrFFY1Y1rzYhun07l3DuCi4yZdvixLlq7m6wk7bca5qDRGM3wLEexfXB5UQtnREsHvcUmDUmaQ/F2HjC9aCcvu9LJbiG4QK0jpTtOq9PE6GQHdmLam0RZGkSPgynVMBSTsa0UBAKiTfae9kJ7ByzCGQxiEIzsbHa3hWrzo/gpd4UC2ABe4RVMY6dyDPcvC+1Q8SPmhSVw+Wn4mh6C49LFHky6ISJWKCLvMli8l0="
  - secure: "PC/yNofUh6pXEPJ8v8BWwN85oEtxyH22rJJXD44iLYhhzc4eooDLOn29bjLeex/jjXzu1rUF0UdFDICaGrdlypsZWOwGZSeG4soMEFDWVSLjEbI2AmjKiQAcIHy9g9o6iPort+mxdEDVzCTiv5Ei0wMCToCFvIqex3F0wpwGcU59Zt3VXWAwoZOQeY4uEbJ++CvO2fKzua2KOoNnK2V/X9YZFKnYGH6qKW46j6j99jqmy0Z4m/2qfAzEIx/AHhWmeLqrrav0Aadhm6D2xMvX5r8WkGFfEPcW9HLR7JA2aGroBk9JAVt7yPrs9Lx8+Y5IMAmPocV/m7tdD1umBffxYquHS9JxImk0KUH6EEBGSGqRiGBwHD7R8LqLA7pOhqfhA5cV8WnG6YpojHwoEogYZxPF3pVQy6W4N7E8ta5v9IdX+bdDsdS8HtLEJRyBu73aMFhIEjzauU3eYvpCOfoU5KtEAyKNetjb2NHkUlOUIHaxtHZ3vhXNmyGsyAOmvm0ILN/dW2OOPXVm8yDiu0CUzHUuqfHvpN3dc7QiaI0LsS2rucPZ8cbZnfTizRpo4KJyntdJQjcYyl8PRjpGuxZZXJaWwdgBwkRm6OvCnoyxi95cpr4FnKcTM2IPPWRsjfZoO5GG37Vd74cB5AGyK2maJHMhWnj9zOlM/uTA0jJI9SQ="


# The installs are in the test stage config.
install:
  - pip install --upgrade pip
  - pip install poetry
  #- pip install tensorflow==$TF_VERSION
  # Work around https://github.com/python-poetry/poetry/issues/602
  - poetry remove tensorflow
  - poetry add tensorflow==$TF_VERSION
  - poetry install -v

script: pytest

jobs:
  include:
    - stage: test
      # test stage defined outside of the config

    - stage: deploy
      # Use the earliest version of things for packaging (for backwards binary compatibility)
      python: 3.6
      env: TF_VERSION=2.0
      install:
        - pip install --upgrade pip
        - pip install poetry
      script: skip

      before_deploy:
        - poetry config http-basic.pypi "$PYPI_USER" "$PYPI_PASS"
        - if [[ $TRAVIS_BRANCH == "master" ]] ; then poetry run python bump_autobuild_version.py; fi
        - poetry build


      deploy:
        - provider: script
          script: poetry publish
          on:
            branch: master
          # Make Travis use the before_deploy outputs here.
          skip_cleanup: true

        - provider: script
          script: poetry publish
          on:
            tags: true
          # Make Travis use the before_deploy outputs here.
          skip_cleanup: true

  exclude:
    - python: 3.8
      env: TF_VERSION=2.0
    - python: 3.8
      env: TF_VERSION=2.1
